return {
    -- "al-kot/typst-preview.nvim",
    -- opts = {
    --     -- your config here
    -- },
    -- config = function()
    --     require("typst-preview").setup({
    --         preview = {
    --             max_width = 80, -- Maximum width of the preview window (columns)
    --             ppi = 144, -- The PPI (pixels per inch) to use for PNG export (high value will affect the performance)
    --             position = "right", -- The position of the preview window relative to the code window
    --         },
    --         statusline = {
    --             enabled = true, -- Show statusline
    --             compile = { -- Last compilation status
    --                 ok = { icon = "", color = "#b8bb26" },
    --                 ko = { icon = "", color = "#fb4943" },
    --             },
    --             page_count = { -- Page count
    --                 color = "#d5c4e1",
    --             },
    --         },
    --     })
    -- end
}
